### ISSUE TITLE
Update Code of conduct

### ISSUE THREAD

**Issue by emmyft** [osc-delft/osc-delft.github.io#1]
Currently this is attached to the OLS CoC - we should update it to at least the TU Delft CoC. 

- [ ] Check if enforcement and reporting guidelines are clear

**Comment by emmyft** [comment]
I had a look at the [TUD CoC](https://d1rkab7tlqy5f1.cloudfront.net/TUDelft/Over_TU_Delft/Strategie/Integriteitsbeleid/COC%20EN.pdf) - I guess all members of the OSC Delft are currently employed(?) by Delft and hence are required to abide by the CoC? 

The reporting policy is at the bottom of [this page](https://www.tudelft.nl/en/about-tu-delft/strategy/integrity-policy/)

Are we OK to, for now, adopt the TUD CoC and the associated reporting and enforcement procedures for OSCD?

**Comment by EstherPlomp** [comment]
Sounds good to me! Maybe you can be a first point of contact and otherwise the integrity office?

**Comment by emmyft** [comment]
Thanks @EstherPlomp 💯 

I just noted that in the [OSC starter kit](https://docs.google.com/document/d/1bcodo-KtT93LRUZCNx-6r_1kZvDRMduh5o5ElKXf3PU/edit) it said:

> Becoming part of the growing network of OSCs means that you adhere to our collective Guiding Principles and Code of Conduct,

Did we know this when we rebranded...? I'm guessing there shouldn't be massive conflicts between the OSC CoC and the TUD one, but someone would need to check.

**Comment by EstherPlomp** [comment]
I don't think there are any conflicts in both codes, but it would be good to mention both? Happy to check at some point whether there are any direct conflicts or grey areas.

**Comment by emmyft** [comment]
Thanks @EstherPlomp  - I think the INOSC CoC is more specific than the TUD CoC.

Specifically - in regards to unacceptable behaviours, the [INOSC CoC](https://osf.io/6gsye/) states:

> -  Discriminating, racist, intimidating, harassing, lewd, demeaning, bullying, stalking, or threatening speech or actions
> - Any real or implied threat of physical harm
> - Unwelcome sexual attention
> - Unwelcome physical contact
> - Sustained disruption of speakers or events (verbally or physically)
> - Retaliation against an individual for reporting harassment or other unacceptable behaviors 
> - Retaliation against an individual for participating in the investigation of a report of harassment or otherunacceptable behaviors - Advocating or encouraging any of the above behaviors
> - Falsely reporting harassment or other unacceptable behaviors

The TUD CoC: 

> - intimidation or sexual harassment
> - discrimination
> - aggression and violence
> - threats
> - bullying
> - gossip.

I propose:
1. Communicate this with the community - by rebranding, we accept that our community will operate under the INOSC Guiding Principles and CoC, in addition to the TU Delft CoC and [Regulation for Complaints Concerning Undersirable behaviour](https://d1rkab7tlqy5f1.cloudfront.net/TUDelft/Over_TU_Delft/Strategie/Integriteitsbeleid/TU%20Delft%20Regulations%20for%20Complaints%20Concerning%20Undesirable%20Behaviour.pdf). If you have any questions or concerns, please feel free to raise this by [X date].

2. update CODE_OF_CONDUCT.md with the adapted text of the INOSC CoC. Specifically the reporting section:

> If someone makes you or anyone else feel unsafe or unwelcome, or if you believe a harassment problem exists,please report it as soon as possible to (one of) the Coordinator(s) of the OSC Emmy Tsang (my email address), either in person or electronically (with the option to remain anonymous). If the person you should report to is the target of the complaint, you may contact the [TU Delft External confidential advisor](https://www.tudelft.nl/en/student/services/confidential-advisor/). 

3. For now, update `INDEX.md` with a CoC section that provides a summary of and links to the two CoCs, as well as reporting procedures (this also address #22)

4. I don't feel capable/safe to handle CoC reports myself - if someone else could volunteer to do it together, please let me know (I'd ask more widely too)
