### ISSUE TITLE
Header members dropdown bug

### ISSUE THREAD

**Issue by emmyft** [osc-delft/osc-delft.github.io#11]
![image](https://user-images.githubusercontent.com/24935760/96617095-75f8c780-1303-11eb-8d13-1abdca73742d.png)

AE works, CEG doesn't, might have something do with header anchoring...?

**Comment by ThorkellMoon** [comment]
I believe this is fixed now. Will need to update the id attributes in subsequent <div> elements for other faculties members.md to match the tags present in includes/default-header.html

**Comment by emmyft** [comment]
Thank you @ThorkellMoon ⭐
