### ISSUE TITLE
Inconsistency in "The Community" menu

### ISSUE THREAD

**Issue by ebrahimifard** [osc-delft/osc-delft.github.io#11]
I think there is an inconsistency in "The Community" menu in the top ribbon. The first three items lead into the same web page (different part of it); however, the fourth item goes to different page. It seems to me a bit inconsistent as we often expect the same behavior from all those items.

**Comment by emmyft** [comment]
This idea has actually been incorporated (despite me forgetting to comment with this before I closed this 😆 )

@all-contributors please add @ebrahimifard for ideas
