### ISSUE TITLE
image banners

### ISSUE THREAD

**Issue by junzis** [osc-delft/osc-delft.github.io#19]
I like the clean web template. Thanks for setting this website up!

However, I am slightly opinionated with the large image banner on each page. It takes almost half of the screen when we open a page. (about 1.5 scrolls with my mouse :smiley: ) 

It's a bit distracting for someone come to the website first. Then people might ignore them after a while, even if they are conveying a messge. I believe this precious space at the top of the page can be used for more important content. Maybe choose one for the homepage and remove/reduce the ones on other pages?

**Comment by emmyft** [comment]
I made it a bit smaller now and it looks better, I think! Thank you for the suggestion 💯

**Comment by emmyft** [comment]
@all-contributors please add @junzis for design and ideas
