### ISSUE TITLE
Inconsistency in "The Community" menu

### ISSUE THREAD

**Issue by ebrahimifard** [osc-delft/osc-delft.github.io#22]
I think there is an inconsistency in "The Community" menu in the top ribbon. The first three items lead into the same web page (different part of it); however, the fourth item goes to different page. It seems to me a bit inconsistent as we often expect the same behavior from all those items.

**Comment by emmyft** [comment]
Good point - unfortunately the Code of Conduct is likely to have to be a link out... I have a few solutions in mind
1. Add a header called Code of Conduct in `index.md`, direct the Code of Conduct dropdown item to that heading. Under the heading we can include a short summary of the CoC, and put a link to the full text, whatever it is eventually (See #1 )

2. Remove the Code of Conduct item in the dropdown and put it up as a separate item on the drop ribbon
