### ISSUE TITLE
joining the community

### ISSUE THREAD

**Issue by ebrahimifard** [osc-delft/osc-delft.github.io#24]
Is becoming a data champion the only way of joining the community? If there are more ways to join and participate, they should also be mentioned in the "Join us" menu.

**Comment by EstherPlomp** [comment]
I think the idea is to abandon the term Data Champions right? So everyone should just be able to join the new community directly?

**Comment by EstherPlomp** [comment]
This could actually be addressed in issue #9

**Comment by emmyft** [comment]
THanks for spotting @EstherPlomp! I'll close this one and continue in #9, if that's OK (:
