### ISSUE TITLE
A definition of the OSC Delft

### ISSUE THREAD

**Issue by emmyft** [osc-delft/osc-delft.github.io#3]
The first line on the front page currently reads "The Open Science Community Delft is a _some definition of what this community is_."

I think a definition of a community in the front page will help people get an overview of what this community is doing/about, before deciding to read on further. Would love to hear your thoughts (: 

We need to update this - what should it say? It would probably make sense to look at what other communities have said about themselves as well. Or maybe this should be some sort of a welcome line instead? All thoughts and ideas welcome!

**Comment by EstherPlomp** [comment]
"a learning community that focuses on the sharing and promoting of Open Science practices."

Maybe something that links it to the Data Champions?
"The Open Science Community Delft is a continuation of the Data Champions Community."
Not sure if that is helpful or distracting though!

**Comment by jurra** [comment]
**Header**
Delft Open Science Community

**Subttitle**
a learning community that focuses on the sharing and promoting of Open Science practices.

**Comment by aecryan** [comment]
Suggest adding a line that indicates we welcome everyone to join... here I think "inclusive" could be a nice addition, with a few minor grammatical changes:

"An inclusive learning community that focuses on sharing and promoting Open Science practices."

**Comment by emmyft** [comment]
I like this- thank you everyone 😍 

I'll put this in as a v1 - we will keep in mind to continue to review and revise this as the community grow 🌱
